name: Docker Image Build CI

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: apurvsinghgautam
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Build and push work docker
        uses: docker/build-push-action@v2
        with:
          context: work_docker
          push: true
          tags: apurvsinghgautam/work:main
